backend:
  name: git-gateway
  branch: main
media_folder: 'public/assets/images'
public_folder: '/assets/images'
collections:
  - name: 'artist'
    title: 'Artist'
    folder: 'src/artists'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Instagram', name: 'instagram', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['artist'] }
